name: Prepare Release Branch

permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  build-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main with full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Prepare release branch from main (remove ONLY root css, scss, .github)
        run: |
          set -e

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git fetch origin

          # main 기준으로 release 브랜치 재생성/리셋
          git checkout -B release origin/main

          # --- 루트 폴더만 제거 ---
          [ -d "./css" ] && rm -rf "./css"
          [ -d "./scss" ] && rm -rf "./scss"
          [ -d "./.github" ] && rm -rf "./.github"

          # 혹시라도 guide/css 삭제가 스테이징되면 되돌림
          git restore --staged --worktree --quiet -- guide/css || true

          # 변경 스테이징
          git add -A

          # 변경이 있을 때만 커밋
          if ! git diff --cached --quiet; then
            git commit -m "chore(release): prepare release branch (drop root css, scss, .github)"
          fi

          # 안전한 강제 푸시
          git push --force-with-lease origin release
